## Lite Payment Service Configuration
spring:
  application:
    name: LitePaymentService
  ##Database configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: liteuser
    password: l1t3s3rvic3
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

## Server configuration
server:
  port: 8086

## External services configuration
services:
  antifraud:
    url: http://localhost:9001/antifraud-validator
  network:
    url: http://localhost:9002/bank-network

## Feing configuration
feign:
  hystrix:
    enabled: false
  client:
    config:
      antifraud:
        connectionTimeout: 5000
        readTimeout: 30000
        loggerLevel: FULL
      network:
        connectionTimeout: 10000
        readTimeout: 30000
        loggerLevel: FULL

## Circuit breaker configuration
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    lite:
      baseConfig: default
      permittedNumberOfCallsInHalfOpenState: 10
      minimumNumberOfCalls: 10
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 25000
      slidingWindowType: TIME_BASED
      slidingWindowSize: 60
      waitDurationInOpenState: 60s
    anti-fraud:
      baseConfig: default
      permittedNumberOfCallsInHalfOpenState: 10
      minimumNumberOfCalls: 10
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 25000
      slidingWindowType: TIME_BASED
      slidingWindowSize: 60
      waitDurationInOpenState: 60s

## Wiremocks configuration
wiremock:
  mocks:
    services:
      antifraud-validator:
        enabled: true
        port: 9001
        resourcesPath: wiremock/antifraudService
      bank-network:
        enabled: true
        port: 9002
        resourcesPath: wiremock/paymentService
