package com.senior.test.litepaymentservice.share.exception;

/**
 * Exception that is generated by business validations.
 *
 * @author <a href='carlos.suarez@payu.com'>Carlos Eduardo Suárez Silvestre</a>
 */
public class PaymentException extends RuntimeException {

	private static final long serialVersionUID = 4804944264789966124L;

	public PaymentException(final String message) {

		super(message);
	}
}
